use starbridge_core::{
    ApprovalRequestRecord, BrowserTaskRecord, ChatThreadRecord, MemoryChunkRecord,
    MemoryDocumentRecord, MemoryEmbeddingRecord, MessageEventRecord, MissionControlSnapshot,
    RetrievalTraceRecord, WorkflowRunRecord, WorkflowStepRecord,
};

pub fn sample_snapshot() -> MissionControlSnapshot {
    MissionControlSnapshot {
        environment: "local control + SpacetimeDB + Vercel edge ingress".to_string(),
        generated_at: "2026-03-27T18:00:00Z".to_string(),
        workflow_runs: vec![
            WorkflowRunRecord {
                run_id: "run_01".to_string(),
                thread_id: "thread_ops".to_string(),
                agent_id: "saturn".to_string(),
                goal: "Investigate workflow replay drift after a failed browser verification.".to_string(),
                priority: "high".to_string(),
                trigger_source: "github".to_string(),
                requested_by: "saturn".to_string(),
                current_stage: "verify".to_string(),
                status: "running".to_string(),
                summary: Some("Browser evidence is being collected before the operator summary is published.".to_string()),
            },
            WorkflowRunRecord {
                run_id: "run_02".to_string(),
                thread_id: "thread_memory".to_string(),
                agent_id: "voyager".to_string(),
                goal: "Compact recent run history into reusable retrieval material.".to_string(),
                priority: "normal".to_string(),
                trigger_source: "web".to_string(),
                requested_by: "symbiex".to_string(),
                current_stage: "learn".to_string(),
                status: "queued".to_string(),
                summary: None,
            },
        ],
        workflow_steps: vec![
            WorkflowStepRecord {
                step_id: "run_01_route".to_string(),
                run_id: "run_01".to_string(),
                agent_id: "saturn".to_string(),
                stage: "route".to_string(),
                owner_execution: "vercel-edge".to_string(),
                status: "completed".to_string(),
                retry_count: 0,
                depends_on_step_id: None,
                runner_id: Some("edge-east-1".to_string()),
            },
            WorkflowStepRecord {
                step_id: "run_01_verify".to_string(),
                run_id: "run_01".to_string(),
                agent_id: "saturn".to_string(),
                stage: "verify".to_string(),
                owner_execution: "browser-worker".to_string(),
                status: "running".to_string(),
                retry_count: 0,
                depends_on_step_id: Some("run_01_act".to_string()),
                runner_id: Some("browser-east-1".to_string()),
            },
            WorkflowStepRecord {
                step_id: "run_01_summarize".to_string(),
                run_id: "run_01".to_string(),
                agent_id: "saturn".to_string(),
                stage: "summarize".to_string(),
                owner_execution: "container-runner".to_string(),
                status: "ready".to_string(),
                retry_count: 0,
                depends_on_step_id: Some("run_01_verify".to_string()),
                runner_id: None,
            },
            WorkflowStepRecord {
                step_id: "run_02_learn".to_string(),
                run_id: "run_02".to_string(),
                agent_id: "voyager".to_string(),
                stage: "learn".to_string(),
                owner_execution: "learning-worker".to_string(),
                status: "ready".to_string(),
                retry_count: 1,
                depends_on_step_id: Some("run_02_summarize".to_string()),
                runner_id: None,
            },
        ],
        browser_tasks: vec![
            BrowserTaskRecord {
                task_id: "browser_01".to_string(),
                run_id: "run_01".to_string(),
                step_id: "run_01_verify".to_string(),
                agent_id: "saturn".to_string(),
                mode: "monitor".to_string(),
                risk: "medium".to_string(),
                status: "running".to_string(),
                owner_execution: "browser-worker".to_string(),
                url: "https://preview.cadet.dev/runs/run_01".to_string(),
            },
            BrowserTaskRecord {
                task_id: "browser_02".to_string(),
                run_id: "run_01".to_string(),
                step_id: "run_01_verify".to_string(),
                agent_id: "saturn".to_string(),
                mode: "read".to_string(),
                risk: "low".to_string(),
                status: "queued".to_string(),
                owner_execution: "browser-worker".to_string(),
                url: "https://github.com/Dexploarer/cadet/pull/1".to_string(),
            },
        ],
        memory_documents: vec![
            MemoryDocumentRecord {
                document_id: "doc_01".to_string(),
                agent_id: "saturn".to_string(),
                namespace: "cadet/workflows".to_string(),
                source_kind: "run-summary".to_string(),
                title: "Workflow replay checklist".to_string(),
                content: "Summaries from failed verify stages should always link the browser task artifacts before the summarize stage advances.".to_string(),
            },
            MemoryDocumentRecord {
                document_id: "doc_02".to_string(),
                agent_id: "voyager".to_string(),
                namespace: "cadet/retrieval".to_string(),
                source_kind: "learning-note".to_string(),
                title: "Memory ranking fallback".to_string(),
                content: "Cosine ranking remains the safe default until native vector indexing is proven in production.".to_string(),
            },
        ],
        memory_chunks: vec![
            MemoryChunkRecord {
                chunk_id: "chunk_01".to_string(),
                document_id: "doc_01".to_string(),
                agent_id: "saturn".to_string(),
                namespace: "cadet/workflows".to_string(),
                ordinal: 0,
                content: "Verify summaries must carry browser artifact references before the summarize stage advances.".to_string(),
                metadata_json: "{\"source\":\"run_01\",\"kind\":\"summary\"}".to_string(),
                created_at_micros: 1774651859000,
            },
            MemoryChunkRecord {
                chunk_id: "chunk_02".to_string(),
                document_id: "doc_01".to_string(),
                agent_id: "saturn".to_string(),
                namespace: "cadet/workflows".to_string(),
                ordinal: 1,
                content: "Approval-heavy verify stages should leave the workflow blocked until operator resolution lands.".to_string(),
                metadata_json: "{\"source\":\"run_01\",\"kind\":\"policy\"}".to_string(),
                created_at_micros: 1774651859200,
            },
            MemoryChunkRecord {
                chunk_id: "chunk_03".to_string(),
                document_id: "doc_02".to_string(),
                agent_id: "voyager".to_string(),
                namespace: "cadet/retrieval".to_string(),
                ordinal: 0,
                content: "Fallback ranking uses deterministic embeddings so every retrieval path stays replayable in tests.".to_string(),
                metadata_json: "{\"source\":\"run_02\",\"kind\":\"retrieval\"}".to_string(),
                created_at_micros: 1774651859400,
            },
            MemoryChunkRecord {
                chunk_id: "chunk_04".to_string(),
                document_id: "doc_02".to_string(),
                agent_id: "voyager".to_string(),
                namespace: "cadet/retrieval".to_string(),
                ordinal: 1,
                content: "Each retrieval trace records both the query vector and the exact chunk lineage selected for a run.".to_string(),
                metadata_json: "{\"source\":\"run_02\",\"kind\":\"trace\"}".to_string(),
                created_at_micros: 1774651859600,
            },
        ],
        memory_embeddings: vec![
            MemoryEmbeddingRecord {
                embedding_id: "embedding_01".to_string(),
                chunk_id: "chunk_01".to_string(),
                agent_id: "saturn".to_string(),
                namespace: "cadet/workflows".to_string(),
                model: "deterministic-v1".to_string(),
                dimensions: 12,
                vector: vec![0.18, 0.34, 0.41, 0.22, 0.19, 0.36, 0.44, 0.27, 0.31, 0.14, 0.39, 0.29],
                checksum: "seed-embedding-01".to_string(),
                created_at_micros: 1774651859800,
            },
            MemoryEmbeddingRecord {
                embedding_id: "embedding_02".to_string(),
                chunk_id: "chunk_02".to_string(),
                agent_id: "saturn".to_string(),
                namespace: "cadet/workflows".to_string(),
                model: "deterministic-v1".to_string(),
                dimensions: 12,
                vector: vec![0.25, 0.29, 0.33, 0.37, 0.21, 0.28, 0.35, 0.4, 0.18, 0.31, 0.24, 0.34],
                checksum: "seed-embedding-02".to_string(),
                created_at_micros: 1774651860000,
            },
            MemoryEmbeddingRecord {
                embedding_id: "embedding_03".to_string(),
                chunk_id: "chunk_03".to_string(),
                agent_id: "voyager".to_string(),
                namespace: "cadet/retrieval".to_string(),
                model: "deterministic-v1".to_string(),
                dimensions: 12,
                vector: vec![0.42, 0.18, 0.24, 0.39, 0.33, 0.15, 0.27, 0.44, 0.21, 0.36, 0.19, 0.28],
                checksum: "seed-embedding-03".to_string(),
                created_at_micros: 1774651860200,
            },
            MemoryEmbeddingRecord {
                embedding_id: "embedding_04".to_string(),
                chunk_id: "chunk_04".to_string(),
                agent_id: "voyager".to_string(),
                namespace: "cadet/retrieval".to_string(),
                model: "deterministic-v1".to_string(),
                dimensions: 12,
                vector: vec![0.31, 0.27, 0.17, 0.41, 0.29, 0.35, 0.22, 0.32, 0.38, 0.26, 0.28, 0.33],
                checksum: "seed-embedding-04".to_string(),
                created_at_micros: 1774651860400,
            },
        ],
        retrieval_traces: vec![RetrievalTraceRecord {
            trace_id: "trace_01".to_string(),
            run_id: "run_01".to_string(),
            step_id: "run_01_plan".to_string(),
            query_text: "workflow replay browser verification artifact contract".to_string(),
            query_embedding: vec![0.28, 0.24, 0.31, 0.34, 0.22, 0.29, 0.4, 0.26, 0.19, 0.37, 0.21, 0.35],
            chunk_ids: vec![
                "chunk_01".to_string(),
                "chunk_03".to_string(),
                "chunk_04".to_string(),
            ],
            metadata_json: "{\"source\":\"seed\",\"kind\":\"query\"}".to_string(),
            created_at_micros: 1774651860600,
        }],
        approval_requests: vec![ApprovalRequestRecord {
            approval_id: "approval_01".to_string(),
            run_id: "run_01".to_string(),
            step_id: "run_01_verify".to_string(),
            agent_id: "saturn".to_string(),
            title: "Approve browser artifact capture".to_string(),
            detail: "The verify stage wants to record browser evidence and attach it to the workflow summary.".to_string(),
            status: "pending".to_string(),
            risk: "medium".to_string(),
            requested_by: "browser-worker".to_string(),
        }],
        threads: vec![
            ChatThreadRecord {
                thread_id: "thread_ops".to_string(),
                channel: "web".to_string(),
                channel_thread_id: "thread_ops".to_string(),
                title: "Operator console".to_string(),
                latest_message_at_micros: 1774651863294,
            },
            ChatThreadRecord {
                thread_id: "thread_memory".to_string(),
                channel: "github".to_string(),
                channel_thread_id: "cadet#42".to_string(),
                title: "Memory rollout".to_string(),
                latest_message_at_micros: 1774651861000,
            },
        ],
        message_events: vec![
            MessageEventRecord {
                event_id: "event_01".to_string(),
                thread_id: "thread_ops".to_string(),
                run_id: Some("run_01".to_string()),
                channel: "web".to_string(),
                direction: "inbound".to_string(),
                actor: "saturn".to_string(),
                content: "Render the new Dioxus mission control against live Spacetime data.".to_string(),
                created_at_micros: 1774651860000,
            },
            MessageEventRecord {
                event_id: "event_02".to_string(),
                thread_id: "thread_ops".to_string(),
                run_id: Some("run_01".to_string()),
                channel: "web".to_string(),
                direction: "outbound".to_string(),
                actor: "saturn".to_string(),
                content: "Verify is running. Browser evidence will post here when the task finishes.".to_string(),
                created_at_micros: 1774651863294,
            },
            MessageEventRecord {
                event_id: "event_03".to_string(),
                thread_id: "thread_memory".to_string(),
                run_id: Some("run_02".to_string()),
                channel: "github".to_string(),
                direction: "inbound".to_string(),
                actor: "symbiex".to_string(),
                content: "Compact recent run history into reusable retrieval material.".to_string(),
                created_at_micros: 1774651860500,
            },
        ],
        trajectory_scores: vec![],
        training_buffer: vec![],
        operator_credits: vec![],
    }
}
